DevOps terminology training
joseph-flinn/devops-training pull request #10
Opened 2021-03-01 06:38 UTC by shaners1106

I feel pretty good about the terminology, however, the last 3 items were a little harder to find quality content on.  If you could look over my Build Pipeline, Release Pipeline and Configuration Management categories to make sure that I didn't miss anything crucial, that would be awesome.

Thank you so much Joseph.

2021-03-01 12:41 UTC, joseph-flinn requested changes

2021-03-01 12:41 UTC, joseph-flinn commented on sprint-1/README.md.save
> +# Sprint 1
I don't think this file should be here.

2021-03-01 12:44 UTC, joseph-flinn commented
@shaners1106 other than the rogue file, this PR looks great. The terms are throughly explored. This exercise was mostly in creating awareness of the different parts of what is automated by a "DevOps Engineer" (I'm not sure if we've talked about the misunderstanding of the term DevOps. DevOps is not a position, it is a philosophy of how to get work done across an organization).

2021-03-01 15:03 UTC, shaners1106 commented
Not sure how that file got inputted, but my hunch is that it was something to do with me still figuring out Nano.  At one point I used ctrl z in Nano and it exited Nano and I was 99% done with the terminology and I thought I had lost it all and was going to have to redo it; I about had a heart attack.  However, luckily I was able to recover it.  Despite the pain, it's still really great practice for me to acclimate myself to new environments.

2021-03-02 18:07 UTC, joseph-flinn approved these changes

2021-03-02 20:25 UTC, merged